### ISSUE TITLE
Update CHANGELOG.md

### ISSUE THREAD

**Issue by crsaracco** [RustAudio/vst-rs#101]
Retroactively update `CHANGELOG.md`:
 - Figure out what "notable" changes happened in each crates.io release, and put that stuff into the changelog file.
 - Format it similar to the format described in ["Keep a Changelog"](https://keepachangelog.com/en/1.0.0/), where needed.

In the future, any releases should have an updated changelog before release.

*[EDIT: never mind about the tagging stuff, we already do that. Removed from the issue.]*

-----

Related:
 - #61 
 - #70 

See also:
 - https://keepachangelog.com/en/1.0.0/
 - https://semver.org/spec/v2.0.0.html

**Comment by piedoom** [comment]
closing with #178
