### ISSUE TITLE
Implement FromStr for CanDo

### ISSUE THREAD

**Issue by crsaracco** [RustAudio/vst-rs#110]
Clippy identified that we should implement the `FromStr` trait for `CanDo` instead of just [making our own `from_str` function](https://github.com/RustAudio/vst-rs/blob/aa7cc43daac810be800741a96a38dea89c8cf25b/src/plugin.rs#L411).

This decision came out of #104, but I didn't want to do it there because it is a slight function signature change. I think it should be pretty easy though.

**Comment by crsaracco** [comment]
Note: see #117 for some discussion.

**Comment by piedoom** [comment]
Closing for now to match the discussion in 117.
