### ISSUE TITLE
Telegram link dead?

### ISSUE THREAD

**Issue by perlindgren** [RustAudio/vst-rs#119]
Hi Folks

I'm new to RustAudio and the vst(2) crate. I tried to join the Telegram group, but got an error that the invinte link had expired. Is the Telegram group removed or moved to somewhere else?

I have loads of other questions as well, but I think they are better discussed in a chat...

See you...

**Comment by Boscop** [comment]
Have you tried the telegram link here? 
https://github.com/RustAudio/vst-rs/wiki#community
It seems to be working..
We also use Discord and Discourse, the links are at the top in the org description here :)
https://github.com/RustAudio

**Comment by perlindgren** [comment]
The Telegram group still reports that the invite has expired.

Discord link worked, but I don't have permission to post. Maybe you need to add me somehow.

I'm `pln` (per.lindgren@ltu.se).
Thanks in advance.

**Comment by perlindgren** [comment]
Sorry I think it was that I was directed to joins and parts and there I could not post. So its all fine and dandy. See you on Discord then.
