### ISSUE TITLE
How to package a VST plugin on linux

### ISSUE THREAD

**Issue by mitermayer** [RustAudio/vst-rs#124]
Hi there,

Thank you for this library! I am currently trying to setup end-to-end development environment. Hoping to build a dummy VST plugin and have it imported in a DAW (bitwig-studio since im on linux) in order to test end to end workflow for local development 

I really wish there was a step by step with a dummy example in the repo, also maybe some build scripts for linux

**Comment by m-hilgendorf** [comment]
Hi @mitermayer 

VST2 plugins are just shared objects (.so) on Linux, so you don't need any additional build scripts. Just point Bitwig's plugin search path to the target build directory in your local crate.
