### ISSUE TITLE
Undefined behavior: zero-initialization of Event

### ISSUE THREAD

**Issue by askeksa** [RustAudio/vst-rs#131]
As I understand it, we need to fix this to prevent this code from panicking in a future version of Rust.

Quoting @RalfJung from the discussion of https://github.com/RustAudio/vst-rs/pull/112:

The bug is here:

https://github.com/RustAudio/vst-rs/blob/d7d5b6f0c049bac923c87ab9d49ca743a8adcb6a/src/api.rs#L488

and here:

https://github.com/RustAudio/vst-rs/blob/d7d5b6f0c049bac923c87ab9d49ca743a8adcb6a/src/api.rs#L503

`EventType` contains no variant with tag discriminant 0, so creating one via `mem::zeroed()` is [Undefined Behavior](https://doc.rust-lang.org/reference/behavior-considered-undefined.html).

**Comment by RalfJung** [comment]
Yes, thanks for opening an issue. :)

The easiest fix is probably to have some variant with discriminant 0, that would then be the one that is used by a `std::mem::zeroed()` event. Alternatively, maybe you could avoid unsafe code entirely and `derive(Default)` for `Event`, and then `impl Default for EventType` to determine what the default event type should be.

**Comment by Boscop** [comment]
I just ran into this, my plugin panics when I try to load it, e.g. in the `simple_host` that's part of the `examples`.
It crashes in this line:
https://github.com/RustAudio/vst-rs/blob/f0b7fd317e590312e55467eaee29f7a813583df2/src/buffer.rs#L397
because `SysExEvent` contains an `EventType`.

Could we please fix this soon? :)
(I really need this VST to function..)

```
thread '<unnamed>' panicked at 'attempted to zero-initialize type `api::SysExEve
nt`, which is invalid', /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5\library\
core\src\mem\mod.rs:623:9
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5\/library\std\src
\panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5\/library\core\sr
c\panicking.rs:85
   2: core::panicking::panic
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5\/library\core\sr
c\panicking.rs:50
   3: core::mem::zeroed
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5\library\core\src
\mem\mod.rs:623
   4: vst::buffer::SendEventBuffer::new
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\vst-
0.2.0\src\buffer.rs:397
   5: vst::buffer::{{impl}}::default
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\vst-
0.2.0\src\buffer.rs:386
```

**Comment by RalfJung** [comment]
Indeed, the UB check that causes a panic here has landed in the mean time. Cc https://github.com/rust-lang/rust/issues/66151

**Comment by askeksa** [comment]
I will take a look at this over the weekend.
