### ISSUE TITLE
 I'm looking for a GUI sample for macos

### ISSUE THREAD

**Issue by YuMuuu** [RustAudio/vst-rs#133]
https://github.com/RustAudio/vst-rs/blob/f0b7fd317e590312e55467eaee29f7a813583df2/src/editor.rs#L28

I understand that there are editor implementations supported on Windows and Mac OS.

I found example for windows.
<https://qiita.com/hatoo@github/items/01d7b5266d4e8787785a>

But could not found example for macos.

And I still don't understand how to use NSView.
e.g. winit don't supported setting children NSView.

please add  /example example of gui for window and macos 　；_；

**Comment by crsaracco** [comment]
Hi @YuMuuu !

One of the goals for `vst-rs` is to be as platform-independent as possible; as of right now, there aren't any GUI solutions that offer a full enough functionality on all three platforms (Windows, Mac OS, and Linux/X11), so we're opting to wait until that happens to give an example of how to use it.

If you're interested, a few of us on [the Discord](https://discord.gg/QPdhk2u) are semi-actively working on getting something working for GUIs. One of the most promising approaches right now seems to be creating our own windowing crate [[1]](https://github.com/RustAudio/baseview), [[2]](https://github.com/antonok-edm/vst_window), and using Iced for graphics [[3]](https://github.com/BillyDM/iced_audio/), [[4]](https://github.com/hatoo/vst-rs-example-iced).

A particularly impressive and recent example is Antonok's [ampli-Fe](https://github.com/antonok-edm/ampli-Fe/), built with his `vst_window` and using `wgpu` for graphics.

**Comment by YuMuuu** [comment]
I joined discode server now.
thanks for link.  reading now!!
