### ISSUE TITLE
how does `open()` in `Editor` work?

### ISSUE THREAD

**Issue by SiebenCorgie** [RustAudio/vst-rs#142]
Hi,

I'm currently trying to build a VST-Host for my application. However, i can not get the plugin's interface to show up. But I have to admit that I'm not really sure which pointer to pass into the `open()` function as a parent.

Is it currently possible to get the interface? If yes, how? Maybe there is some sample code in an existing open-source project?

Thanks for any help!
cheers

**Comment by schell** [comment]
I think the pointer should be the raw window handle, which will be different on each OS. There's a bit about it in the wiki: https://github.com/RustAudio/vst-rs/wiki/VST2-Guis

**Comment by k-bx** [comment]
Has anyone figured this one out? Here are my failed attempts on macOS https://github.com/k-bx/diminuendo-vsthost/blob/main/src/main.rs

**Comment by crsaracco** [comment]
@schell is correct, the wiki's info is accurate AFAIK.

It's a platform-specific window, so you have to create the window with your platform's "native" window API. In Windows, for example, I've used the `winapi` crate to get a window working.

I have a bunch of really old examples at https://github.com/crsaracco/vst2-gui-prototypes -- I don't really touch this crate all too much anymore though, so my memory of the details of getting this working is fading. (I also didn't get too far on MacOS, unfortunately.)

**Comment by piedoom** [comment]
Closing as the question has been answered. For anyone looking, take a look at baseview, iced-audio, etc. Lots of GUI options now as well.
