### ISSUE TITLE
Compatibility with Apple Silicon (M1) architecture

### ISSUE THREAD

**Issue by gyopiazza** [RustAudio/vst-rs#173]
Hello! I can successfully compile the example VSTs on the M1 chip but they are not showing in the DAWs. I'm not sure if it's a compatibility issue with the Apple Silicon architecture or maybe it's something else.

Thank you for this project, I really hope I can play with it soon :)

**Comment by schell** [comment]
I ran into this as well. For me the problem was that the DAW was **not** an arm64 application, so it didn't see the arm64 compiled VST as an option. I had to cross compile my VST. This may not be the same for you, of course, but that's what I ran into.

**Comment by gyopiazza** [comment]
Thanks a lot @schell, that was indeed the problem!
