### ISSUE TITLE
Consider re-exporting `num-traits` and `num_enum`

### ISSUE THREAD

**Issue by piedoom** [RustAudio/vst-rs#181]
Given the crate consumer will very likely be constructing their own tagged enums, should we re-export both the crates we use internally since they'll likely be imported anyways?

**Comment by askeksa** [comment]
Hmm, I don't know... I have a handful of crates using `vst-rs`, and none of them use any of these crates.

Isn't re-exporting most customarily used when types from a dependency appear in the API of a crate? Is that the case here?

**Comment by piedoom** [comment]
I would argue that we do, as parameters are accessed via a numeric ID, and I think tagged enums are the idiomatic way to do such in rust. All that being said, i've since learned the bigger picture re: licensing issues with VST2 and don't think it's worth putting more work into this repo & instead redirecting it towards VST3 efforts/CLAP

**Comment by glowcoil** [comment]
I don't think there's much benefit to re-exporting these crates, since they're not exposed in any part of the public crate API. If users need the same functionality they can just those crates as a dependency, and if the versions are compatible Cargo will only include one copy of them anyway.
