### ISSUE TITLE
Roadmap for version 0.1.0 release

### ISSUE THREAD

**Issue by Walther** [RustAudio/vst-rs#83]
As a rust-vst crate developer, I want to know which issues are prioritized & required to be completed for the milestone of crate release version 0.1.0. We should have a roadmap, in one form or another, that defines what is in scope for that release.

The ideas and questions from https://github.com/rust-dsp/rust-vst/issues/81 should be itemized and decisions made on which ones are considered blockers for the next release.

Roadmap(s) for future releases & details for the ideas and issues for those can be tracked in other issues.

**Comment by Walther** [comment]
One possible attempt at a roadmap for this version: https://github.com/rust-dsp/rust-vst/projects/2

Todo:
- Define tasks that are required to be completed before a 0.1.0 release, with small and actionable scope
- Add those cards to the todo lane of the milestone board
- Complete those cards

**Comment by piedoom** [comment]
May want to rename this since our published version is 0.1.0

**Comment by Walther** [comment]
I'll just close this issue & the project board. It seems that the roadmap / project board hasn't been used a single time since they were created 🙂 No need to keep a tool for a tool's sake.
