### ISSUE TITLE
Written comparison of possible GUI approaches, with pros and cons

### ISSUE THREAD

**Issue by Walther** [RustAudio/vst-rs#84]
As a rust-vst developer, I would like to see a document that lists out all the possible GUI approaches with their pros and cons. The list should clearly outline any blockers and assumptions made for those blockers, and speculations for possible workarounds or fixes to said blockers.

Requirement for #82 

There's some text written here in the wiki: https://github.com/rust-dsp/rust-vst/wiki/Rust-Audio-GUI-Development-Progress

**Comment by Walther** [comment]
E.g. something like (note: this is just a rough draft example)

`winit`
- concerns over window creation and ownership
  - otoh, recent work for supporting reusing windows? https://github.com/tomaka/glutin/issues/175 -> https://github.com/tomaka/winit/issues/33 -> https://github.com/tomaka/winit/pull/797
- concerns over the event loop

`druid`

`conrod`

etc...

**Comment by crsaracco** [comment]
I made https://github.com/crsaracco/vst2-gui-research a while ago -- I think that would be an appropriate place to collect this sort of information.
