### ISSUE TITLE
remove api::events_raw()

### ISSUE THREAD

**Issue by crsaracco** [RustAudio/vst-rs#98]
TODO:

 - Make sure [all of these cases](https://github.com/search?q=events_raw+extension%3Ars) still work with some replacement code
 - Remove `api::events_raw()`
 - Bump release version

See my comments on #93 for more context.

**Comment by askeksa** [comment]
It would make sense to include this in the 0.2.0 release. None of the crates you link to are compatible with the thread safety change, so they will need to be updated anyway. And this change is a fairly simple one for them.

**Comment by crsaracco** [comment]
Yep, I was thinking the same thing.
